name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - imagens/ditadoraladin.jpg
    - imagens/ondevivemmonstros.jpg
    - imagens/ratatoing.jpg
    - imagens/kungfusao.jpg
    - imagens/Penasemfundo.png
    - imagens/skyhd.jpeg
